#!/usr/bin/env python3
"""Build the site icons from the real boundary of parcel 64-17.

The outline is read live from the Sumter County tax parcel layer and projected
to Web Mercator at true orientation, so the icon is the same shape, the same way
up, as the site map draws. Re-run if the county record changes:

    python3 tools/build-favicon.py

Writes website/assets/favicon.svg and website/assets/icons/*.png. PNG output needs
rsvg-convert (librsvg); the SVG alone is written if it is missing.
"""
import json
import math
import shutil
import subprocess
import urllib.parse
import urllib.request
from pathlib import Path

PARCEL_LAYER = ('https://ga31portal.kcsgis.com/ga31server/rest/services/'
                'Public/Sumter_Parcels/MapServer/1/query')
PARCEL_ID = ' 64     17'

INK = '#171a18'      # --ink
ORANGE = '#e55726'   # --orange
BOX = 64
EARTH_RADIUS = 6378137.0

# name -> (pixels, inset as a fraction of the box)
# Maskable icons are inset so the parcel survives Android's circular crop.
PNG_SIZES = {
    'icon-16.png': (16, 0.0),
    'icon-32.png': (32, 0.0),
    'icon-180.png': (180, 0.0),      # apple-touch-icon
    'icon-192.png': (192, 0.0),
    'icon-512.png': (512, 0.0),
    'icon-192-maskable.png': (192, 0.18),
    'icon-512-maskable.png': (512, 0.18),
}


def fetch_ring():
    query = urllib.parse.urlencode({
        'where': f"PARCELID = '{PARCEL_ID}'",
        'outFields': 'PARCELID',
        'outSR': '4326',
        'f': 'geojson',
        'returnGeometry': 'true',
    })
    with urllib.request.urlopen(f'{PARCEL_LAYER}?{query}', timeout=60) as response:
        data = json.load(response)
    geometry = data['features'][0]['geometry']
    rings = geometry['coordinates'][0] if geometry['type'] == 'MultiPolygon' else geometry['coordinates']
    return rings[0] if isinstance(rings[0][0], list) else rings


def mercator(lon, lat):
    return (EARTH_RADIUS * math.radians(lon),
            EARTH_RADIUS * math.log(math.tan(math.pi / 4 + math.radians(lat) / 2)))


def outline_path(ring, span, tolerance=0.7):
    """Project, centre, scale to `span` px wide, and drop sub-pixel vertices."""
    points = [mercator(lon, lat) for lon, lat in ring]
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    cx, cy = (min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2
    scale = span / (max(xs) - min(xs))
    # Mercator y grows north, SVG y grows down.
    placed = [(BOX / 2 + (x - cx) * scale, BOX / 2 + (cy - y) * scale) for x, y in points]

    kept = [placed[0]]
    for point in placed[1:]:
        if math.dist(point, kept[-1]) >= tolerance:
            kept.append(point)
    if math.dist(kept[0], kept[-1]) < tolerance and len(kept) > 3:
        kept.pop()
    return 'M' + ' L'.join(f'{x:.2f} {y:.2f}' for x, y in kept) + ' Z', len(placed), len(kept)


def svg_document(path, radius=14):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" role="img" aria-label="Sumter Field Desk">
  <title>Sumter Field Desk — parcel 64-17</title>
  <!--
    Generated by tools/build-favicon.py. The outline is the real surveyed
    boundary of parcel 64-17 (301 Brady Rd, 125.1 acres) from the Sumter County
    tax parcel layer, projected to Web Mercator at true orientation.
    Do not hand-edit: re-run the script instead.
  -->
  <rect width="{BOX}" height="{BOX}" rx="{radius}" fill="{INK}"/>
  <path d="{path}" fill="{ORANGE}"/>
</svg>
'''


def main():
    assets = Path(__file__).resolve().parent.parent / 'website' / 'assets'
    icons = assets / 'icons'
    icons.mkdir(exist_ok=True)

    ring = fetch_ring()
    path, before, after = outline_path(ring, span=56)
    (assets / 'favicon.svg').write_text(svg_document(path))
    print(f'favicon.svg written ({before} vertices simplified to {after})')

    rsvg = shutil.which('rsvg-convert')
    if not rsvg:
        print('rsvg-convert not found; skipped PNG icons (install librsvg)')
        return

    for name, (size, inset) in PNG_SIZES.items():
        if inset:
            # Shrink the artwork inside a full-bleed square for maskable icons.
            inner, _, _ = outline_path(ring, span=56 * (1 - 2 * inset))
            source = assets / f'.{name}.svg'
            source.write_text(svg_document(inner, radius=0))
        else:
            source = assets / 'favicon.svg'
        subprocess.run([rsvg, '-w', str(size), '-h', str(size), str(source),
                        '-o', str(icons / name)], check=True)
        if inset:
            source.unlink()
        print(f'  icons/{name} ({size}px)')


if __name__ == '__main__':
    main()
