#!/usr/bin/env python3
"""Vendor the web fonts into website/assets/fonts/.

The site loaded Newsreader and DM Mono from fonts.googleapis.com, which meant
two requests to Google on every page view — including the research notes and
the meeting calendar, which otherwise touch no third party at all. Leaflet is
vendored here for the same reason, and the recap player waits for a click
before it will talk to YouTube; the fonts were the last per-visit call left.

What this does: ask Google for the same stylesheet the browser would get,
download every .woff2 it names, and rewrite the @font-face rules to point at
the local copies. The unicode-range declarations are kept exactly as served, so
a reader who never types Vietnamese never downloads the Vietnamese subset.

Re-run after changing a weight or adding a family:

    python3 tools/vendor-fonts.py

Then commit the changed files under website/assets/fonts/.
"""

import re
import sys
import urllib.request
from pathlib import Path

# The exact request the browser used to make. Keep this in step with the
# weights styles.css actually asks for: 400/500 mono, 400/600/700 serif.
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=DM+Mono:wght@400;500"
    "&family=Newsreader:opsz,wght@6..72,400;6..72,600;6..72,700"
    "&display=swap"
)

# Without a modern UA, Google serves .ttf instead of .woff2 — several times the
# bytes, for a format every browser this site supports replaced years ago.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

REPO = Path(__file__).resolve().parent.parent
FONT_DIR = REPO / "website" / "assets" / "fonts"
CSS_OUT = REPO / "website" / "assets" / "fonts.css"

HEADER = """/* Generated by tools/vendor-fonts.py — do not edit by hand.

   Local copies of Newsreader and DM Mono, so a page view makes no request to
   Google. The unicode-range rules are Google's own: a browser downloads only
   the subsets it needs for the text on the page.

   Newsreader is the variable font (optical size 6-72, weight 200-800), so one
   file covers every weight and size the site uses. Only upright faces are
   vendored, matching what the hosted stylesheet served; italic is synthesised
   by the browser, exactly as it was before. */
"""


def fetch(url: str, binary: bool = False):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = response.read()
    return payload if binary else payload.decode("utf-8")


def main() -> int:
    css = fetch(CSS_URL)
    # Each face arrives as "/* subset */ @font-face { ... }". Parse the whole
    # block rather than zipping three separate findall results: those go out of
    # step the moment a family declares a face the others do not.
    faces = []
    for subset, block in re.findall(r"/\*\s*([\w\[\]-]+)\s*\*/\s*@font-face\s*{([^}]*)}", css):
        url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block)
        family = re.search(r"font-family:\s*'([^']+)'", block)
        weight = re.search(r"font-weight:\s*([\d\s]+);", block)
        if url and family:
            faces.append({
                "url": url.group(1),
                "slug": family.group(1).lower().replace(" ", "-"),
                "weight": (weight.group(1).strip() if weight else "400").replace(" ", "-"),
                "subset": subset,
            })
    if not faces:
        print("No @font-face blocks found — did the css2 API change?", file=sys.stderr)
        return 1

    # A variable font serves one file for every weight, so the same URL appears
    # under several font-weight values. Those must share one filename, or the
    # file is downloaded once per weight. A static family serves a different
    # file per weight, and those must NOT share one — the first write would be
    # silently overwritten by the next, leaving every weight pointing at the
    # last one downloaded.
    weights_per_url = {}
    for face in faces:
        weights_per_url.setdefault(face["url"], set()).add(face["weight"])

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    written = {}
    for face in faces:
        if face["url"] in written:
            continue
        variable = len(weights_per_url[face["url"]]) > 1
        name = (f"{face['slug']}-{face['subset']}.woff2" if variable
                else f"{face['slug']}-{face['weight']}-{face['subset']}.woff2")
        (FONT_DIR / name).write_bytes(fetch(face["url"], binary=True))
        written[face["url"]] = name
        print(f"  {name}  ({(FONT_DIR / name).stat().st_size // 1024} KB)")

    local = css
    for url, name in written.items():
        local = local.replace(url, f"/assets/fonts/{name}")
    CSS_OUT.write_text(HEADER + "\n" + local)
    print(f"Wrote {CSS_OUT.relative_to(REPO)} with {len(written)} faces.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
